using Newtonsoft.Json;
using System;

namespace Mandrill.Models
{
  /// <summary>
  /// Time series statistics for a Mandrill template.
  /// </summary>
  public class TemplateTimeSeries
  {
    #region Public Properties

    /// <summary>
    /// The date and time that this series corresponds to.
    /// </summary>
    [JsonProperty("time")]
    public DateTime Time { get; set; }

    /// <summary>
    /// The number of emails that were sent during the hour.
    /// </summary>
    [JsonProperty("sent")]
    public int Sent { get; set; }

    /// <summary>
    /// The number of emails that hard bounced during the hour.
    /// </summary>
    [JsonProperty("hard_bounces")]
    public int HardBounces { get; set; }

    /// <summary>
    /// The number of emails that soft bounced during the hour.
    /// </summary>
    [JsonProperty("soft_bounces")]
    public int SoftBounces { get; set; }

    /// <summary>
    /// The number of emails that were rejected during the hour.
    /// </summary>
    [JsonProperty("rejects")]
    public int Rejects { get; set; }

    /// <summary>
    /// The number of spam complaints received during the hour.
    /// </summary>
    [JsonProperty("complaints")]
    public int Complaints { get; set; }

    /// <summary>
    /// The number of emails opened during the hour.
    /// </summary>
    [JsonProperty("opens")]
    public int Opens { get; set; }

    /// <summary>
    /// The number of unique opens generated by messages sent during the hour.
    /// </summary>
    [JsonProperty("unique_opens")]
    public int UniqueOpens { get; set; }

    /// <summary>
    /// The number of tracked URLs clicked during the hour.
    /// </summary>
    [JsonProperty("clicks")]
    public int Clicks { get; set; }

    /// <summary>
    /// The number of unique clicks generated by messages sent during the hour.
    /// </summary>
    [JsonProperty("unique_clicks")]
    public int UniqueClicks { get; set; }

    #endregion
  }
}
